messages:
  start: "Отлично, ты на шаг ближе к своим целям! 🌟
\n\nДля того чтобы я могла стать твоим наиболее эффективным помощником, мне нужно узнать некоторые детали о тебе. Поделись, пожалуйста, своим именем, возрастом, ростом, весом, уровнем твоей активности и целями, которых ты хочешь достичь. Эта информация важна, чтобы я могла предложить тебе персонализированные советы и рекомендации, которые будут учитывать все твои индивидуальные особенности и нужды.
\nЯ обещаю обращаться с твоими личными данными с максимальной заботой и конфиденциальностью. Они будут использоваться исключительно для того, чтобы делать мои советы максимально полезными и эффективными для тебя.
\nКогда будешь готов(а), нажми на кнопку ниже и введи свои данные. Давай вместе шаг за шагом приближаться к твоей мечте! 💖
\n\n👇 Нажми здесь, чтобы ввести свои данные и начать! 👇
"

keyboard:
  add_profile: "О боте"
  edit_profile: "..."
