messages:
  start: "Slim Foto - этот бот поможет вам похудеть, он считает калорийность и БЖУ блюд по фотографиям и записывает в дневник и дает рекомендации по питанию.

\n<b>Как пользоваться:</?b>

\n1. Нажмите настройки и запишите свои данные и цель.
\n2. Нажмите “подсчет каллорий”, загрузите фото и краткое описание блюда (например плов с говядиной или освяноблин)
\n3. Нажмите “добавить запись” чтобы сохранить результат в дневник
\n4. Нажмите “Неправильный подсчет” если результат, по вашему мнению, отличается более чем на 10% от истины
\n5. Кнопка “дневник” чтобы смотреть результаты "

keyboard:
  add_profile: "О боте"
  edit_profile: "..."
